export const POINTAGE_ERRORS = {
  sessionExpired: 'Session expiree.',
  startFailed: 'Impossible de demarrer le pointage.',
  startInvalidParams: 'Parametres de demarrage invalides.',
  invalidSession: 'Session invalide.',
  sessionNotFound: 'Session introuvable.',
  invalidPause: 'Pause invalide.',
  invalidPauseForSession: 'Pause invalide pour cette session.',
  pauseNotFound: 'Pause introuvable.',
  pauseFailed: 'Impossible de mettre le pointage en pause.',
  resumeFailed: 'Impossible de reprendre le pointage.',
  stopFailed: "Impossible d'arreter le pointage.",
  validateFailed: 'Impossible de valider le pointage.',
  invalidPointageDate: 'Date de pointage invalide.',
  statusEnCoursMissing: "Statut 'EN_COURS' introuvable.",
  heartbeatFailed: "Impossible d'actualiser le pointage.",
  autoClosureFailed: 'Impossible de verifier la fermeture automatique.',
  rolloverInvalidParams: 'Parametres de bascule invalides.',
  rolloverCurrentPointageMissing: 'Pointage courant introuvable.',
  rolloverClosePauseFailed: 'Impossible de cloturer la pause de la veille.',
  rolloverCloseSessionFailed: 'Impossible de cloturer la session de la veille.',
  rolloverPrepareFailed: 'Impossible de preparer le pointage du nouveau jour.',
  rolloverOpenSessionFailed: "Impossible d'ouvrir la session du nouveau jour.",
  rolloverOpenPauseFailed: "Impossible d'ouvrir la pause du nouveau jour.",
  rolloverFailed: 'Impossible de basculer le pointage au nouveau jour.',
} as const

