-- Transition utilisateur.actif -> utilisateur.id_statut_utilisateur
-- Migration idempotente.

create table if not exists public.statut_utilisateur (
  id_statut_utilisateur integer generated by default as identity primary key,
  code_statut_utilisateur text not null unique,
  libelle_statut_utilisateur text null
);

insert into public.statut_utilisateur (code_statut_utilisateur, libelle_statut_utilisateur)
values
  ('ACTIVE', 'Compte actif'),
  ('DESACTIVE', 'Compte desactive'),
  ('EN_ATTENTE', 'Compte en attente')
on conflict (code_statut_utilisateur) do update
set libelle_statut_utilisateur = excluded.libelle_statut_utilisateur;

alter table public.utilisateur
add column if not exists id_statut_utilisateur integer null;

do $$
declare
  v_has_actif_col boolean;
begin
  select exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'utilisateur'
      and column_name = 'actif'
  ) into v_has_actif_col;

  if v_has_actif_col then
    execute $sql$
      update public.utilisateur u
      set id_statut_utilisateur = su.id_statut_utilisateur
      from public.statut_utilisateur su
      where u.id_statut_utilisateur is null
        and (
          (u.actif is true and su.code_statut_utilisateur = 'ACTIVE')
          or (u.actif is false and su.code_statut_utilisateur = 'DESACTIVE')
        )
    $sql$;
  end if;
end;
$$;

update public.utilisateur u
set id_statut_utilisateur = su.id_statut_utilisateur
from public.statut_utilisateur su
where u.id_statut_utilisateur is null
  and su.code_statut_utilisateur = 'EN_ATTENTE';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'utilisateur_id_statut_utilisateur_fkey'
      and conrelid = 'public.utilisateur'::regclass
  ) then
    alter table public.utilisateur
    add constraint utilisateur_id_statut_utilisateur_fkey
    foreign key (id_statut_utilisateur)
    references public.statut_utilisateur(id_statut_utilisateur);
  end if;
end;
$$;

alter table public.utilisateur
alter column id_statut_utilisateur set not null;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'utilisateur'
      and column_name = 'actif'
  ) then
    alter table public.utilisateur
    drop column actif;
  end if;
end;
$$;

create or replace function public.assign_system_task_to_user()
returns trigger
language plpgsql
as $$
declare
  v_system_task_id integer;
  v_is_active boolean;
begin
  select exists (
    select 1
    from public.statut_utilisateur su
    where su.id_statut_utilisateur = new.id_statut_utilisateur
      and su.code_statut_utilisateur = 'ACTIVE'
  )
  into v_is_active;

  if coalesce(v_is_active, false) is not true then
    return new;
  end if;

  select t.id_tache
  into v_system_task_id
  from public.tache t
  where t.tache_systeme = true
    and t.actif = true
  order by t.id_tache asc
  limit 1;

  if v_system_task_id is null then
    return new;
  end if;

  insert into public.utilisateur_tache (id_utilisateur, id_tache)
  values (new.id_utilisateur, v_system_task_id)
  on conflict do nothing;

  return new;
end;
$$;

drop trigger if exists trg_assign_system_task_to_user on public.utilisateur;

create trigger trg_assign_system_task_to_user
after insert or update of id_statut_utilisateur on public.utilisateur
for each row
execute function public.assign_system_task_to_user();

insert into public.utilisateur_tache (id_utilisateur, id_tache)
select u.id_utilisateur, t.id_tache
from public.utilisateur u
join public.statut_utilisateur su
  on su.id_statut_utilisateur = u.id_statut_utilisateur
 and su.code_statut_utilisateur = 'ACTIVE'
join public.tache t on t.tache_systeme = true and t.actif = true
where not exists (
  select 1
  from public.utilisateur_tache ut
  where ut.id_utilisateur = u.id_utilisateur
    and ut.id_tache = t.id_tache
);

